#!/usr/bin/env node
/**
 * @variantree/watcher — CLI
 *
 * On-demand mode: no background watcher needed.
 * Every command reads the conversation from OpenCode's SQLite on demand.
 */

import { Command } from 'commander';
import chalk from 'chalk';
import path from 'node:path';
import fsSync from 'node:fs';
import { VariantTree } from '@variantree/core';
import { NodeStorage } from './node/storage.js';
import { NodeBlobStore } from './node/blob-store.js';
import { NodeFileSystem } from './node/fs-adapter.js';
import { OpenCodeAdapter } from './adapters/opencode.js';
import { MessageDiffer } from './differ.js';
import { VariantreeWatcher } from './watcher.js';

// ─── Theme ────────────────────────────────────────────────────────────────

const WORKSPACE_ID = 'default';

const brand = chalk.hex('#A78BFA');       // purple
const accent = chalk.hex('#34D399');      // green
const dim = chalk.dim;
const warn = chalk.hex('#FBBF24');        // amber
const err = chalk.hex('#F87171');         // red
const info = chalk.hex('#60A5FA');        // blue

const LOGO = brand('◆ variantree');
const CHECK = accent('✓');
const CROSS = err('✗');
const DOT = dim('•');
const ARROW = dim('→');
const BRANCH_ICON = brand('⎇');
const SNAP_ICON = '📸';
const MSG_ICON = info('💬');
const TREE_VERT = dim('│');
const TREE_FORK = dim('├─');
const TREE_END = dim('└─');

// ─── Helpers ──────────────────────────────────────────────────────────────

function header(text: string) {
  console.log('');
  console.log(`  ${LOGO}  ${dim('·')}  ${text}`);
  console.log('');
}

function success(text: string) {
  console.log(`  ${CHECK} ${text}`);
}

function detail(label: string, value: string) {
  console.log(`    ${dim(label.padEnd(14))} ${value}`);
}

function errorMsg(text: string) {
  console.log(`  ${CROSS} ${err(text)}`);
}

function hint(text: string) {
  console.log(`  ${dim(text)}`);
}

function divider() {
  console.log('');
}

/** Build a fully-configured engine (with snapshot adapters). */
function createEngine(cwd: string) {
  const storage = new NodeStorage(cwd);
  const engine = new VariantTree({
    storage,
    snapshotStorage: new NodeBlobStore(cwd),
    fileSystem: new NodeFileSystem(),
  });
  return { engine, storage };
}

/** Load or auto-initialise workspace. */
async function ensureWorkspace(cwd: string) {
  const { engine, storage } = createEngine(cwd);
  let ws = await engine.loadWorkspace(WORKSPACE_ID);
  if (!ws) {
    ws = await engine.createWorkspace('My Project');
    ws.id = WORKSPACE_ID;
    await storage.save(WORKSPACE_ID, ws);
    await engine.loadWorkspace(WORKSPACE_ID);
    console.log(`  ${dim('workspace initialised')}`);
  }
  return { engine, storage };
}

/** Sync the latest conversation from OpenCode's SQLite into the Variantree branch. */
async function syncConversation(engine: VariantTree, cwd: string) {
  const adapter = new OpenCodeAdapter();
  const messages = await adapter.readMessagesAsync(cwd);
  if (messages.length === 0) return 0;

  const existing = engine.getContext();
  const differ = new MessageDiffer();
  differ.diff(existing);
  const newMessages = differ.diff(messages);

  for (const msg of newMessages) {
    await engine.addMessage(msg.role, msg.content, { source: 'opencode' });
  }
  return newMessages.length;
}

/** Generate .variantree/branch-context.md */
function generateContextFile(cwd: string, branchName: string, messages: Array<{ role: string; content: string }>) {
  const contextDir = path.join(cwd, '.variantree');
  if (!fsSync.existsSync(contextDir)) fsSync.mkdirSync(contextDir, { recursive: true });

  const lines: string[] = [
    `# Variantree Branch Context`,
    ``,
    `**Branch:** ${branchName}`,
    `**Generated:** ${new Date().toISOString()}`,
    ``,
    `> This file was auto-generated by Variantree. It contains the conversation`,
    `> history up to the point where this branch was created. Read this to`,
    `> understand the context of what has been done so far.`,
    ``,
    `---`,
    ``,
    `## Conversation History`,
    ``,
  ];

  if (messages.length === 0) {
    lines.push('_No messages recorded at this checkpoint._');
  } else {
    for (const msg of messages) {
      const prefix = msg.role === 'user' ? '**User:**' : '**Assistant:**';
      const content = msg.content.length > 500
        ? msg.content.slice(0, 500) + '...'
        : msg.content;
      lines.push(`${prefix} ${content}`, '');
    }
  }

  const filePath = path.join(contextDir, 'branch-context.md');
  fsSync.writeFileSync(filePath, lines.join('\n'), 'utf8');
  return filePath;
}

function formatTime(ts: number) {
  const d = new Date(ts);
  const now = new Date();
  const diff = now.getTime() - d.getTime();
  if (diff < 60_000) return 'just now';
  if (diff < 3_600_000) return `${Math.floor(diff / 60_000)}m ago`;
  if (diff < 86_400_000) return `${Math.floor(diff / 3_600_000)}h ago`;
  return d.toLocaleDateString();
}

// ─── CLI ──────────────────────────────────────────────────────────────────

const program = new Command();
program
  .name('variantree')
  .description(brand('Version control for AI conversations'))
  .version('0.1.0');

// ── init ──────────────────────────────────────────────────────────────────
program
  .command('init')
  .description('Initialise a Variantree workspace')
  .option('-d, --dir <path>', 'workspace directory', process.cwd())
  .action(async (opts) => {
    const cwd = path.resolve(opts.dir);
    header('init');
    await ensureWorkspace(cwd);
    success('Workspace ready');

    // Auto-configure OpenCode MCP
    const opencodePath = path.join(cwd, 'opencode.json');
    let hasMcp = false;
    
    try {
      const devServerPath = path.join(cwd, 'packages', 'mcp', 'src', 'server.ts');
      const isDev = fsSync.existsSync(devServerPath);
      const command = isDev 
        ? ["npx", "tsx", "packages/mcp/src/server.ts"] 
        : ["npx", "-y", "@variantree/mcp"];

      const mcpConfig = {
        type: "local",
        command,
        environment: { VARIANTREE_DIR: "." }
      };

      if (fsSync.existsSync(opencodePath)) {
        const existingInfo = JSON.parse(fsSync.readFileSync(opencodePath, 'utf8'));
        if (!existingInfo.mcp) existingInfo.mcp = {};
        if (!existingInfo.mcp.variantree) {
           existingInfo.mcp.variantree = mcpConfig;
           fsSync.writeFileSync(opencodePath, JSON.stringify(existingInfo, null, 2), 'utf8');
           hasMcp = true;
           success('OpenCode MCP server added to existing opencode.json');
        } else {
           hint('OpenCode MCP configuration already exists');
        }
      } else {
         const newConfig = {
            "$schema": "https://opencode.ai/config.json",
            mcp: { variantree: mcpConfig }
         };
         fsSync.writeFileSync(opencodePath, JSON.stringify(newConfig, null, 2), 'utf8');
         hasMcp = true;
         success('Created opencode.json with Variantree MCP server');
      }
    } catch (err) {
      hint('Could not auto-configure opencode.json. You may need to add the MCP server manually.');
    }

    hint(`Run ${chalk.white('variantree checkpoint "label"')} after coding to save your progress`);
    divider();
  });

// ── checkpoint ────────────────────────────────────────────────────────────
program
  .command('checkpoint <label>')
  .description('Sync conversation from OpenCode + snapshot code')
  .option('-d, --dir <path>', 'workspace directory', process.cwd())
  .action(async (label: string, opts) => {
    const cwd = path.resolve(opts.dir);
    header('checkpoint');
    const { engine } = await ensureWorkspace(cwd);

    const synced = await syncConversation(engine, cwd);
    if (synced > 0) {
      detail('synced', `${MSG_ICON} ${synced} message(s) from OpenCode`);
    }

    await engine.createCheckpoint(label, { workspacePath: cwd });
    success(`Checkpoint ${chalk.white.bold(`"${label}"`)} created`);
    detail('snapshot', `${SNAP_ICON} code saved`);
    divider();
  });

// ── branch ────────────────────────────────────────────────────────────────
program
  .command('branch <name>')
  .description('Create a branch, restore code, and generate context')
  .option('-d, --dir <path>', 'workspace directory', process.cwd())
  .option('-c, --checkpoint <label>', 'branch from a specific checkpoint (default: latest)')
  .action(async (name: string, opts) => {
    const cwd = path.resolve(opts.dir);
    header('branch');
    const { engine } = await ensureWorkspace(cwd);
    await syncConversation(engine, cwd);

    const checkpoints = engine.getCheckpoints();
    let cpId: string | undefined;
    let cpLabel = 'current position';

    if (opts.checkpoint) {
      const cp = checkpoints.find((c) => c.label === opts.checkpoint);
      if (!cp) { errorMsg(`Checkpoint "${opts.checkpoint}" not found.`); process.exit(1); }
      cpId = cp.id;
      cpLabel = cp.label;
    } else if (checkpoints.length > 0) {
      const lastCp = checkpoints[checkpoints.length - 1];
      cpId = lastCp.id;
      cpLabel = lastCp.label;
    }

    await engine.branch(name, cpId);
    success(`Branch ${brand.bold(`"${name}"`)} created from ${dim(`"${cpLabel}"`)}`);

    if (cpId) {
      const summary = await engine.restoreCheckpoint(cpId, cwd);
      if (summary) {
        detail('restored', `${summary.written.length} written, ${summary.deleted.length} deleted, ${summary.skipped.length} unchanged`);
      }
    }

    const context = engine.getContext();
    const contextPath = generateContextFile(cwd, name, context);
    detail('context', path.relative(cwd, contextPath));

    divider();
    console.log(`  ${warn('⚡')} ${chalk.white('Next steps:')}`);
    console.log(`     1. Restart OpenCode ${dim('(quit and reopen)')}`);
    console.log(`     2. Tell it: ${info('"Read .variantree/branch-context.md for context"')}`);
    divider();
  });

// ── restore ───────────────────────────────────────────────────────────────
program
  .command('restore <label>')
  .description('Restore code to a checkpoint + generate context')
  .option('-d, --dir <path>', 'workspace directory', process.cwd())
  .action(async (label: string, opts) => {
    const cwd = path.resolve(opts.dir);
    header('restore');
    const { engine } = await ensureWorkspace(cwd);

    const checkpoints = engine.getCheckpoints();
    const cp = checkpoints.find((c) => c.label === label);
    if (!cp) { errorMsg(`Checkpoint "${label}" not found.`); process.exit(1); }

    const summary = await engine.restoreCheckpoint(cp.id, cwd);
    if (summary) {
      success(`Restored to ${chalk.white.bold(`"${label}"`)}`);
      detail('written', `${summary.written.length} file(s)`);
      detail('deleted', `${summary.deleted.length} file(s)`);
      detail('unchanged', `${summary.skipped.length} file(s)`);
    } else {
      success(`Switched to ${chalk.white.bold(`"${label}"`)} ${dim('(no code snapshot)')}`);
    }

    const context = engine.getContext();
    const branchName = engine.getActiveBranch().name;
    const contextPath = generateContextFile(cwd, branchName, context);
    detail('context', path.relative(cwd, contextPath));

    divider();
    console.log(`  ${warn('⚡')} ${chalk.white('Next steps:')}`);
    console.log(`     1. Restart OpenCode ${dim('(quit and reopen)')}`);
    console.log(`     2. Tell it: ${info('"Read .variantree/branch-context.md for context"')}`);
    divider();
  });

// ── status ────────────────────────────────────────────────────────────────
program
  .command('status')
  .description('Show active branch, messages, and checkpoints')
  .option('-d, --dir <path>', 'workspace directory', process.cwd())
  .action(async (opts) => {
    const cwd = path.resolve(opts.dir);
    const { engine } = createEngine(cwd);
    const ws = await engine.loadWorkspace(WORKSPACE_ID);
    if (!ws) {
      header('status');
      hint('No workspace found.');
      hint(`Run ${chalk.white('variantree init')} or ${chalk.white('variantree checkpoint "label"')} to get started.`);
      divider();
      return;
    }

    const branch = engine.getActiveBranch();
    const context = engine.getContext();
    const branches = engine.getBranches();
    const checkpoints = engine.getCheckpoints();

    header('status');

    // Branch info
    console.log(`  ${BRANCH_ICON}  ${chalk.white.bold(branch.name)}  ${dim(`(${context.length} messages)`)}`);
    divider();

    // All branches
    if (branches.length > 1) {
      console.log(`  ${dim('Branches')}`);
      for (const b of branches) {
        const active = b.isActive ? accent(' ← active') : '';
        const icon = b.isActive ? accent('●') : dim('○');
        console.log(`    ${icon} ${b.name} ${dim(`(${b.messageCount} msgs)`)}${active}`);
      }
      divider();
    }

    // Checkpoints
    if (checkpoints.length === 0) {
      console.log(`  ${dim('No checkpoints yet.')}`);
      hint(`Run ${chalk.white('variantree checkpoint "label"')} to save your progress.`);
    } else {
      console.log(`  ${dim('Checkpoints')}`);
      for (const cp of checkpoints.slice(-8)) {
        const snap = cp.snapshot ? ` ${SNAP_ICON}` : '';
        const time = dim(formatTime(cp.createdAt));
        console.log(`    ${DOT} ${chalk.white(cp.label)}${snap}  ${time}`);
      }
    }
    divider();
  });

// ── tree ──────────────────────────────────────────────────────────────────
program
  .command('tree')
  .description('Visualise the branch tree')
  .option('-d, --dir <path>', 'workspace directory', process.cwd())
  .action(async (opts) => {
    const cwd = path.resolve(opts.dir);
    const { engine } = createEngine(cwd);
    const ws = await engine.loadWorkspace(WORKSPACE_ID);
    if (!ws) {
      header('tree');
      hint('No workspace found.');
      divider();
      return;
    }

    const branches = engine.getBranches();
    const checkpoints = engine.getCheckpoints();

    header('tree');

    for (let i = 0; i < branches.length; i++) {
      const b = branches[i];
      const isLast = i === branches.length - 1;
      const prefix = i === 0 ? accent('●') : dim('○');
      const nameColor = b.isActive ? accent : chalk.white;
      const activeTag = b.isActive ? accent(' ← you are here') : '';

      console.log(`  ${prefix} ${nameColor.bold(b.name)}${activeTag} ${dim(`(${b.messageCount} msgs)`)}`);

      // Show checkpoints on this branch
      const branchCps = checkpoints.filter((cp) => cp.branchId === b.id);
      for (let j = 0; j < branchCps.length; j++) {
        const cp = branchCps[j];
        const cpIsLast = j === branchCps.length - 1 && isLast;
        const connector = cpIsLast ? TREE_END : TREE_FORK;
        const snap = cp.snapshot ? ` ${SNAP_ICON}` : '';
        console.log(`  ${TREE_VERT}  ${connector} ${warn(cp.label)}${snap}`);
      }

      if (!isLast) {
        console.log(`  ${TREE_VERT}`);
      }
    }
    divider();
  });

// ── watch (optional) ──────────────────────────────────────────────────────
program
  .command('watch')
  .description('(Optional) Real-time watcher for web UI')
  .option('-d, --dir <path>', 'workspace directory', process.cwd())
  .action(async (opts) => {
    const cwd = path.resolve(opts.dir);
    header('watch');
    const { engine } = await ensureWorkspace(cwd);

    const watcher = new VariantreeWatcher({
      workspacePath: cwd,
      adapter: new OpenCodeAdapter(),
      engine,
      onSync: (count) => console.log(`  ${MSG_ICON} Synced ${accent(String(count))} message(s)`),
      onError: (e) => console.error(`  ${CROSS} ${e.message}`),
    });

    await watcher.start();
    console.log(`  ${dim('Watching for changes... Press')} ${chalk.white('Ctrl+C')} ${dim('to stop.')}`);
    divider();

    process.on('SIGINT', async () => {
      await watcher.stop();
      console.log(`\n  ${dim('Watcher stopped.')}`);
      divider();
      process.exit(0);
    });
  });

program.parse();
