#!/usr/bin/env node
/**
 * @variantree/mcp — MCP Server
 *
 * Exposes Variantree operations as MCP tools that AI coding assistants
 * (OpenCode, Claude Code, etc.) can call during conversations.
 *
 * Transport: stdio (spawned as child process by the host).
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import path from 'node:path';
import fs from 'node:fs';
import { VariantTree } from '@variantree/core';
import {
  NodeStorage,
  NodeBlobStore,
  NodeFileSystem,
  OpenCodeAdapter,
  MessageDiffer,
} from '@variantree/watcher';

// ─── Shared Helpers ───────────────────────────────────────────────────────

const WORKSPACE_ID = 'default';

function getCwd(): string {
  return process.env.VARIANTREE_DIR
    ? path.resolve(process.env.VARIANTREE_DIR)
    : process.cwd();
}

function createEngine(cwd: string) {
  const storage = new NodeStorage(cwd);
  const engine = new VariantTree({
    storage,
    snapshotStorage: new NodeBlobStore(cwd),
    fileSystem: new NodeFileSystem(),
  });
  return { engine, storage };
}

async function ensureWorkspace(cwd: string) {
  const { engine, storage } = createEngine(cwd);
  let ws = await engine.loadWorkspace(WORKSPACE_ID);
  if (!ws) {
    ws = await engine.createWorkspace('My Project');
    ws.id = WORKSPACE_ID;
    await storage.save(WORKSPACE_ID, ws);
    await engine.loadWorkspace(WORKSPACE_ID);
  }
  return { engine, storage };
}

async function syncConversation(engine: VariantTree, cwd: string): Promise<number> {
  const adapter = new OpenCodeAdapter();
  const messages = await adapter.readMessagesAsync(cwd);
  if (messages.length === 0) return 0;

  const existing = engine.getContext();
  const differ = new MessageDiffer();
  differ.diff(existing);
  const newMessages = differ.diff(messages);

  for (const msg of newMessages) {
    await engine.addMessage(msg.role, msg.content, { source: 'opencode' });
  }
  return newMessages.length;
}

function generateContextFile(cwd: string, branchName: string, messages: Array<{ role: string; content: string }>) {
  const contextDir = path.join(cwd, '.variantree');
  if (!fs.existsSync(contextDir)) fs.mkdirSync(contextDir, { recursive: true });

  const lines = [
    `# Variantree Branch Context`,
    ``,
    `**Branch:** ${branchName}`,
    `**Generated:** ${new Date().toISOString()}`,
    ``,
    `> Auto-generated by Variantree. Read this for context on prior work.`,
    ``,
    `---`,
    ``,
    `## Conversation History`,
    ``,
  ];

  for (const msg of messages) {
    const prefix = msg.role === 'user' ? '**User:**' : '**Assistant:**';
    const content = msg.content.length > 500 ? msg.content.slice(0, 500) + '...' : msg.content;
    lines.push(`${prefix} ${content}`, '');
  }

  fs.writeFileSync(path.join(contextDir, 'branch-context.md'), lines.join('\n'), 'utf8');
}

// ─── MCP Server ───────────────────────────────────────────────────────────

const server = new McpServer({
  name: 'variantree',
  version: '0.1.0',
});

// ── checkpoint ─────────────────────────────────────────────────

// @ts-expect-error — MCP SDK's Zod type inference is excessively deep (TS2589)
server.tool(
  'checkpoint',
  'Create a Variantree checkpoint: syncs the current conversation from the AI coding tool and takes a snapshot of all code files. Use this when the user wants to save progress.',
  { label: z.string().describe('A short label for this checkpoint, e.g. "auth-working"') },
  async ({ label }) => {
    const cwd = getCwd();
    const { engine } = await ensureWorkspace(cwd);
    const synced = await syncConversation(engine, cwd);
    await engine.createCheckpoint(label, { workspacePath: cwd });

    const lines = [`✓ Checkpoint "${label}" created with code snapshot.`];
    if (synced > 0) lines.push(`  Synced ${synced} message(s).`);
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── branch ─────────────────────────────────────────────────────

server.tool(
  'branch',
  'Create a new Variantree branch. Restores code to the checkpoint state and generates a context file for the new session.',
  {
    name: z.string().describe('Branch name, e.g. "try-graphql"'),
    checkpoint: z.string().optional().describe('Checkpoint label to branch from. Defaults to latest.'),
  },
  async ({ name, checkpoint }) => {
    const cwd = getCwd();
    const { engine } = await ensureWorkspace(cwd);
    await syncConversation(engine, cwd);

    let cpId: string | undefined;
    let cpLabel = 'current state';

    if (checkpoint) {
      const allCheckpoints = engine.getCheckpoints();
      const cp = allCheckpoints.find((c) => c.label === checkpoint);
      if (!cp) {
        return { content: [{ type: 'text' as const, text: `✗ Checkpoint "${checkpoint}" not found. Available: ${allCheckpoints.map((c) => c.label).join(', ') || 'none'}` }] };
      }
      cpId = cp.id;
      cpLabel = cp.label;
    }

    // Branch will auto-checkpoint if cpId is undefined
    const branch = await engine.branch(name, cpId);
    const lines = [`✓ Branch "${name}" created from ${checkpoint ? `"${cpLabel}"` : 'current un-checkpointed state'}.`];

    // Only restore files if we explicitly branched from an older timeframe
    if (cpId && checkpoint) {
      const summary = await engine.restoreCheckpoint(cpId, cwd);
      if (summary) {
        lines.push(`  Restored backward: ${summary.written.length} files written, ${summary.deleted.length} deleted.`);
      }
    }

    generateContextFile(cwd, name, engine.getContext());
    lines.push(`  Context: .variantree/branch-context.md`);
    lines.push(`⚡ Restart the session and read .variantree/branch-context.md for prior context.`);
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── switch ─────────────────────────────────────────────────────

server.tool(
  'switch',
  'Switch to an existing Variantree branch. This will overwrite your files with the branch\'s latest checkpoint and generate a new context file.',
  { name: z.string().describe('Name of the existing branch to switch to, e.g. "main" or "dev"') },
  async ({ name }) => {
    const cwd = getCwd();
    const { engine } = await ensureWorkspace(cwd);

    const branches = engine.getBranches();
    const targetBranch = branches.find((b) => b.name === name);
    if (!targetBranch) {
      return { content: [{ type: 'text' as const, text: `✗ Branch "${name}" not found. Available: ${branches.map(b => b.name).join(', ')}` }] };
    }

    if (targetBranch.isActive) {
      return { content: [{ type: 'text' as const, text: `Already on branch "${name}".` }] };
    }

    await engine.switchBranch(targetBranch.id);

    const checkpoints = engine.getCheckpoints().filter(c => c.branchId === targetBranch.id);
    const latestCp = checkpoints[checkpoints.length - 1];
    const lines = [`✓ Switched to branch "${name}".`];

    if (latestCp) {
       const summary = await engine.restoreCheckpoint(latestCp.id, cwd);
       if (summary) {
         lines.push(`  Restored to checkpoint "${latestCp.label}": ${summary.written.length} files written, ${summary.deleted.length} deleted.`);
       }
    } else {
       lines.push(`  (No checkpoints found on this branch to restore state.)`);
    }

    generateContextFile(cwd, name, engine.getContext());
    lines.push(`  Context updated: .variantree/branch-context.md`);
    lines.push(`⚡ CRITICAL: You must restart OpenCode (or clear your session) and read .variantree/branch-context.md to load the new branch context!`);

    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── restore ────────────────────────────────────────────────────

server.tool(
  'restore',
  'Restore code files to the state at a specific checkpoint. Generates a context file with conversation history.',
  { label: z.string().describe('Checkpoint label to restore to') },
  async ({ label }) => {
    const cwd = getCwd();
    const { engine } = await ensureWorkspace(cwd);

    const cp = engine.getCheckpoints().find((c) => c.label === label);
    if (!cp) {
      return { content: [{ type: 'text' as const, text: `✗ Checkpoint "${label}" not found.` }] };
    }

    const summary = await engine.restoreCheckpoint(cp.id, cwd);
    const lines: string[] = [];

    if (summary) {
      lines.push(`✓ Restored to "${label}": ${summary.written.length} written, ${summary.deleted.length} deleted.`);
    } else {
      lines.push(`✓ Switched to "${label}" (no snapshot).`);
    }

    generateContextFile(cwd, engine.getActiveBranch().name, engine.getContext());
    lines.push(`  Context updated: .variantree/branch-context.md`);
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── status ─────────────────────────────────────────────────────

server.tool(
  'status',
  'Show current Variantree status: active branch, messages, all branches, and checkpoints.',
  {},
  async () => {
    const cwd = getCwd();
    const { engine } = createEngine(cwd);
    const ws = await engine.loadWorkspace(WORKSPACE_ID);
    if (!ws) {
      return { content: [{ type: 'text' as const, text: 'No Variantree workspace. Use variantree_checkpoint to create one.' }] };
    }

    await syncConversation(engine, cwd);
    const branch = engine.getActiveBranch();
    const context = engine.getContext();
    const branches = engine.getBranches();
    const checkpoints = engine.getCheckpoints();

    const lines = [
      `Branch: ${branch.name}`,
      `Messages: ${context.length}`,
      `Branches: ${branches.map((b) => `${b.name}${b.isActive ? ' (active)' : ''}`).join(', ')}`,
    ];

    if (checkpoints.length > 0) {
      lines.push('Checkpoints:');
      for (const cp of checkpoints.slice(-8)) {
        lines.push(`  • ${cp.label}${cp.snapshot ? ' 📸' : ''}`);
      }
    } else {
      lines.push('Checkpoints: none');
    }
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── tree ───────────────────────────────────────────────────────

server.tool(
  'tree',
  'Show ASCII visualization of the branch/checkpoint tree.',
  {},
  async () => {
    const cwd = getCwd();
    const { engine } = createEngine(cwd);
    const ws = await engine.loadWorkspace(WORKSPACE_ID);
    if (!ws) {
      return { content: [{ type: 'text' as const, text: 'No Variantree workspace.' }] };
    }

    const branches = engine.getBranches();
    const checkpoints = engine.getCheckpoints();
    const lines: string[] = [];

    for (let i = 0; i < branches.length; i++) {
      const b = branches[i];
      lines.push(`${b.isActive ? '●' : '○'} ${b.name}${b.isActive ? ' ← active' : ''} (${b.messageCount} msgs)`);
      for (const cp of checkpoints.filter((c) => c.branchId === b.id)) {
        lines.push(`│  ├─ ${cp.label}${cp.snapshot ? ' 📸' : ''}`);
      }
      if (i < branches.length - 1) lines.push('│');
    }
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── Start ─────────────────────────────────────────────────────────────────

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('[variantree-mcp] Server running on stdio');
}

main().catch((err) => {
  console.error('[variantree-mcp] Fatal:', err);
  process.exit(1);
});
