#!/usr/bin/env node
/**
 * @variantree/mcp — MCP Server
 *
 * Exposes Variantree operations as MCP tools that AI coding assistants
 * (OpenCode, Claude Code, etc.) can call during conversations.
 *
 * Transport: stdio (spawned as child process by the host).
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import path from 'node:path';
import fs from 'node:fs';
import { VariantTree } from '@variantree/core';
import {
  NodeStorage,
  GitSnapshotProvider,
  ensureProjectInstructions,
  syncConversation,
  openWebUi,
} from '@variantree/watcher';

// ─── Shared Helpers ───────────────────────────────────────────────────────

const WORKSPACE_ID = 'default';

function getCwd(): string {
  return process.env.VARIANTREE_DIR
    ? path.resolve(process.env.VARIANTREE_DIR)
    : process.cwd();
}

function createEngine(cwd: string) {
  const storage = new NodeStorage(cwd);
  const snapshotProvider = new GitSnapshotProvider(cwd);
  const engine = new VariantTree({
    storage,
    snapshotProvider,
  });
  return { engine, storage, snapshotProvider };
}

async function ensureWorkspace(cwd: string) {
  const { engine, storage, snapshotProvider } = createEngine(cwd);
  let ws = await engine.loadWorkspace(WORKSPACE_ID);
  if (!ws) {
    ws = await engine.createWorkspace('My Project');
    ws.id = WORKSPACE_ID;
    await storage.save(WORKSPACE_ID, ws);
    await engine.loadWorkspace(WORKSPACE_ID);
  }
  return { engine, storage, snapshotProvider };
}

/**
 * Detect which AI tool is calling us.
 * Priority: VARIANTREE_CALLER env var (set by postinstall) > project-dir heuristic.
 */
function detectCallerTool(cwd: string): string | null {
  const caller = process.env.VARIANTREE_CALLER;
  if (caller === 'claudecode' || caller === 'opencode') return caller;

  const home = process.env.HOME ?? process.env.USERPROFILE ?? '';
  const claudeProjectDir = path.join(home, '.claude', 'projects', cwd.replace(/\//g, '-'));
  if (fs.existsSync(claudeProjectDir)) return 'claudecode';
  if (fs.existsSync(path.join(home, '.config', 'opencode', 'sessions'))) return 'opencode';

  return null;
}

/**
 * Sync conversation, then write instructions only for the detected tool.
 *
 * The host that spawned us (VARIANTREE_CALLER / project-dir heuristic) is the
 * source of truth for which instructions file to write. The sync adapter only
 * tells us where messages happen to live — a user who once ran OpenCode in
 * this cwd would otherwise get AGENTS.md written inside a Claude Code session.
 */
async function syncAndEnsureInstructions(engine: VariantTree, cwd: string): Promise<number> {
  const callerTool = detectCallerTool(cwd);
  const result = await syncConversation(engine, cwd, callerTool);
  const toolName = callerTool ?? result.adapterName;
  if (toolName) {
    ensureProjectInstructions(cwd, toolName);
  }
  return result.newMessages;
}



function generateContextFile(cwd: string, branchName: string, summary: string | undefined) {
  const contextDir = path.join(cwd, '.variantree');
  if (!fs.existsSync(contextDir)) fs.mkdirSync(contextDir, { recursive: true });

  const lines = [
    `# Variantree Branch Context`,
    ``,
    `**Branch:** ${branchName}`,
    `**Generated:** ${new Date().toISOString()}`,
    ``,
    `> Auto-generated by Variantree. Read this for context on prior work.`,
    ``,
    `---`,
    ``,
  ];

  if (summary) {
    lines.push(`## Summary`, ``, summary, ``);
  } else {
    lines.push(`No checkpoint summary available. Use the \`log\` tool for full history.`);
  }

  fs.writeFileSync(path.join(contextDir, 'branch-context.md'), lines.join('\n'), 'utf8');
}

/**
 * Count messages on the active branch that have been added since the last checkpoint.
 * These would be lost if the user switches/branches without checkpointing first.
 */
function countUnsavedMessages(engine: VariantTree): number {
  const branch = engine.getActiveBranch();
  const branchCheckpoints = engine
    .getCheckpointsForBranch(branch.id)
    .sort((a, b) => a.createdAt - b.createdAt);
  if (branchCheckpoints.length === 0) return branch.messages.length;
  const lastCp = branchCheckpoints[branchCheckpoints.length - 1];
  return Math.max(0, branch.messages.length - 1 - lastCp.messageIndex);
}

/**
 * Build the lightweight context block injected on switch/restore/branch.
 * Uses the checkpoint summary (tiny, ~100 tokens) instead of full message history.
 * Points the AI to the `log` tool for deeper context.
 */
function generateContextBlock(branchName: string, summary: string | undefined): string {
  const lines = [
    `--- Branch Context ("${branchName}") ---`,
  ];

  if (summary) {
    lines.push(`Summary: ${summary}`);
  } else {
    lines.push(`No checkpoint summary available for this branch.`);
  }

  lines.push(`Tip: Use the \`log\` tool to see the full conversation history if you need more detail on past decisions.`);
  lines.push(`--- End Branch Context ---`);
  return lines.join('\n');
}

// ─── MCP Server ───────────────────────────────────────────────────────────

const server = new McpServer({
  name: 'variantree',
  version: '0.1.0',
});

// ── checkpoint ─────────────────────────────────────────────────
server.registerTool(
  'checkpoint',
  {
    description: 'Create a Variantree checkpoint: syncs the current conversation and takes a code snapshot. ' +
      'You MUST provide a summary of the work done so far — this is injected as context when switching branches. ' +
      'Always relay the full output to the user including messages synced count, snapshot diff, and total file count.',
    inputSchema: {
      label: z.string().describe('A short label for this checkpoint, e.g. "auth-working"'),
      summary: z.string().describe(
        'A concise summary (2-4 sentences) of the work done up to this point. ' +
        'Include key decisions, what was built, and any important context. ' +
        'This summary is injected when switching branches so the AI understands the prior work. ' +
        'Example: "Implemented JWT auth with bcrypt hashing. Login returns access+refresh tokens. Middleware validates on all /api routes."'
      ),
    },
  },
  async ({ label, summary }) => {
    const cwd = getCwd();
    const { engine, snapshotProvider } = await ensureWorkspace(cwd);
    const synced = await syncAndEnsureInstructions(engine, cwd);
    const cp = await engine.createCheckpoint(label, { workspacePath: cwd, summary });

    const totalMessages = engine.getContext().length;
    const lines = [`✓ Checkpoint "${label}" created.`];
    lines.push(`  Messages synced: ${synced} new  (${totalMessages} total in context)`);
    lines.push(`  Summary saved: "${summary}"`);

    if (cp.snapshotRef) {
      const allCheckpoints = engine.getCheckpoints();
      const activeBranch = engine.getActiveBranch();

      const prevCp =
        allCheckpoints
          .filter(c => c.id !== cp.id && c.branchId === cp.branchId && c.snapshotRef)
          .sort((a, b) => b.createdAt - a.createdAt)[0] ??
        (activeBranch.parentCheckpointId
          ? allCheckpoints.find(c => c.id === activeBranch.parentCheckpointId && c.snapshotRef)
          : undefined);

      if (prevCp?.snapshotRef) {
        const diff = await snapshotProvider.diffRefs(prevCp.snapshotRef, cp.snapshotRef);
        const fileCount = diff.added.length + diff.modified.length + diff.unchanged.length;
        const parts = [];
        if (diff.added.length > 0) parts.push(`+${diff.added.length} added`);
        if (diff.modified.length > 0) parts.push(`~${diff.modified.length} modified`);
        if (diff.deleted.length > 0) parts.push(`-${diff.deleted.length} deleted`);
        lines.push(`  Snapshot: ${parts.length > 0 ? parts.join('  ') : 'no file changes'}  (${fileCount} files total)`);
      } else {
        const fileCount = await snapshotProvider.getSnapshotFileCount(cp.snapshotRef);
        lines.push(`  Snapshot: ${fileCount} files`);
      }
    }
    lines.push('');
    lines.push('💡 Run /compact now to compress conversation context before switching branches.');
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── branch ─────────────────────────────────────────────────────

server.registerTool(
  'branch',
  {
    description: 'Create a new Variantree branch. Restores code to the checkpoint state and provides prior conversation context. Always relay the full output including files restored and the conversation context summary. If the tool returns an unsaved-message warning, STOP and ask the user whether to checkpoint first or discard — do NOT silently pass force: true.',
    inputSchema: {
      name: z.string().describe('Branch name, e.g. "try-graphql"'),
      checkpoint: z.string().optional().describe('Checkpoint label to branch from. Defaults to latest on the active branch.'),
      force: z.boolean().optional().describe('Skip the unsaved-work guard. Only pass true AFTER explicitly asking the user and they confirmed they want to discard the unsaved messages.'),
    },
  },
  async ({ name, checkpoint, force }) => {
    const cwd = getCwd();
    const { engine } = await ensureWorkspace(cwd);
    await syncAndEnsureInstructions(engine, cwd);

    // Guard: warn if there are messages not yet captured in a checkpoint
    if (!force) {
      const unsaved = countUnsavedMessages(engine);
      if (unsaved > 0) {
        const activeBranch = engine.getActiveBranch();
        return { content: [{ type: 'text' as const, text:
          `⚠ ${unsaved} message(s) on "${activeBranch.name}" are not checkpointed and won't carry over to "${name}".\n` +
          `  Call checkpoint("<label>") first to save them, then call branch again.\n` +
          `  Or pass force: true to branch without saving.`,
        }]};
      }
    }

    let cpId: string | undefined;
    let cpLabel = 'current state';

    if (checkpoint) {
      const allCheckpoints = engine.getCheckpoints();
      const cp = allCheckpoints.find((c) => c.label === checkpoint);
      if (!cp) {
        return { content: [{ type: 'text' as const, text: `✗ Checkpoint "${checkpoint}" not found. Available: ${allCheckpoints.map((c) => c.label).join(', ') || 'none'}` }] };
      }
      cpId = cp.id;
      cpLabel = cp.label;
    }

    // Branch will auto-checkpoint if cpId is undefined
    const branch = await engine.branch(name, cpId);
    const lines = [
      `✓ Branch "${name}" created from ${checkpoint ? `"${cpLabel}"` : 'current un-checkpointed state'} and switched to it.`,
    ];

    // Only restore files if we explicitly branched from an older checkpoint
    if (cpId && checkpoint) {
      const summary = await engine.restoreCheckpoint(cpId, cwd);
      // restoreCheckpoint switches to the checkpoint's parent branch as a side effect —
      // switch back to the newly created branch
      await engine.switchBranch(branch.id);
      if (summary) {
        lines.push(`  Restored backward: ${summary.written.length} files written, ${summary.deleted.length} deleted.`);
      }
    }

    // Find the most recent checkpoint on the source branch for its summary
    const allCps = engine.getCheckpoints();
    const sourceCp = cpId
      ? allCps.find(c => c.id === cpId)
      : allCps.filter(c => c.branchId !== branch.id).sort((a, b) => b.createdAt - a.createdAt)[0];
    const summary = sourceCp?.summary;

    generateContextFile(cwd, name, summary);
    lines.push(`  Context updated: .variantree/branch-context.md`);
    lines.push(`  No session restart is needed.`);

    const contextBlock = generateContextBlock(name, summary);
    return { content: [
      { type: 'text' as const, text: lines.join('\n') },
      { type: 'text' as const, text: contextBlock },
    ] };
  }
);

// ── switch ─────────────────────────────────────────────────────

server.registerTool(
  'switch',
  {
    description: 'Switch to an existing Variantree branch. Restores files to the branch\'s latest checkpoint and provides prior conversation context. Always relay the full output including files restored and the conversation context summary. If the tool returns an unsaved-message warning, STOP and ask the user whether to checkpoint first or discard — do NOT silently pass force: true.',
    inputSchema: {
      name: z.string().describe('Name of the existing branch to switch to, e.g. "main" or "dev"'),
      force: z.boolean().optional().describe('Skip the unsaved-work guard. Only pass true AFTER explicitly asking the user and they confirmed they want to discard the unsaved messages.'),
    },
  },
  async ({ name, force }) => {
    const cwd = getCwd();
    const { engine } = await ensureWorkspace(cwd);
    await syncAndEnsureInstructions(engine, cwd);

    const branches = engine.getBranches();
    const targetBranch = branches.find((b) => b.name === name);
    if (!targetBranch) {
      return { content: [{ type: 'text' as const, text: `✗ Branch "${name}" not found. Available: ${branches.map(b => b.name).join(', ')}` }] };
    }

    if (targetBranch.isActive) {
      return { content: [{ type: 'text' as const, text: `Already on branch "${name}".` }] };
    }

    // Guard: warn if there are messages not yet captured in a checkpoint
    if (!force) {
      const unsaved = countUnsavedMessages(engine);
      if (unsaved > 0) {
        const activeBranch = engine.getActiveBranch();
        return { content: [{ type: 'text' as const, text:
          `⚠ ${unsaved} message(s) on "${activeBranch.name}" are not checkpointed and will be lost when switching to "${name}".\n` +
          `  Call checkpoint("<label>") first to save them, then call switch again.\n` +
          `  Or pass force: true to switch without saving.`,
        }]};
      }
    }

    await engine.switchBranch(targetBranch.id);

    const checkpoints = engine.getCheckpoints().filter(c => c.branchId === targetBranch.id);
    const latestCp = checkpoints[checkpoints.length - 1];
    const lines = [`✓ Switched to branch "${name}".`];

    if (latestCp) {
       const summary = await engine.restoreCheckpoint(latestCp.id, cwd);
       if (summary) {
         lines.push(`  Restored to checkpoint "${latestCp.label}": ${summary.written.length} files written, ${summary.deleted.length} deleted.`);
       }
    } else {
       lines.push(`  (No checkpoints found on this branch to restore state.)`);
    }

    // Use the latest checkpoint's summary for lightweight context injection
    const summary = latestCp?.summary;
    generateContextFile(cwd, name, summary);
    lines.push(`  Context updated: .variantree/branch-context.md`);
    lines.push(`  No session restart is needed.`);

    const contextBlock = generateContextBlock(name, summary);
    return { content: [
      { type: 'text' as const, text: lines.join('\n') },
      { type: 'text' as const, text: contextBlock },
    ] };
  }
);

// ── restore ────────────────────────────────────────────────────

server.registerTool(
  'restore',
  {
    description: 'Restore code files to the state at a specific checkpoint and provide conversation context. Always relay the full output including files written/deleted and the conversation context summary. If the tool returns an unsaved-message warning, STOP and ask the user whether to checkpoint first or discard — do NOT silently pass force: true.',
    inputSchema: {
      label: z.string().describe('Checkpoint label to restore to'),
      force: z.boolean().optional().describe('Skip the unsaved-work guard. Only pass true AFTER explicitly asking the user and they confirmed they want to discard the unsaved messages.'),
    },
  },
  async ({ label, force }) => {
    const cwd = getCwd();
    const { engine } = await ensureWorkspace(cwd);
    await syncAndEnsureInstructions(engine, cwd);

    // Guard: warn if there are messages not yet captured in a checkpoint
    if (!force) {
      const unsaved = countUnsavedMessages(engine);
      if (unsaved > 0) {
        const activeBranch = engine.getActiveBranch();
        return { content: [{ type: 'text' as const, text:
          `⚠ ${unsaved} message(s) on "${activeBranch.name}" are not checkpointed and will be lost after restoring to "${label}".\n` +
          `  Call checkpoint("<label>") first to save them, then call restore again.\n` +
          `  Or pass force: true to restore without saving.`,
        }]};
      }
    }

    const cp = engine.getCheckpoints().find((c) => c.label === label);
    if (!cp) {
      return { content: [{ type: 'text' as const, text: `✗ Checkpoint "${label}" not found.` }] };
    }

    const summary = await engine.restoreCheckpoint(cp.id, cwd);
    const lines: string[] = [];

    if (summary) {
      lines.push(`✓ Restored to "${label}": ${summary.written.length} written, ${summary.deleted.length} deleted.`);
    } else {
      lines.push(`✓ Switched to "${label}" (no snapshot).`);
    }

    const branchName = engine.getActiveBranch().name;
    // Use the restored checkpoint's summary for lightweight context injection
    const cpSummary = cp.summary;
    generateContextFile(cwd, branchName, cpSummary);
    lines.push(`  Context updated: .variantree/branch-context.md`);
    lines.push(`  No session restart is needed.`);

    const contextBlock = generateContextBlock(branchName, cpSummary);
    return { content: [
      { type: 'text' as const, text: lines.join('\n') },
      { type: 'text' as const, text: contextBlock },
    ] };
  }
);

// ── log ────────────────────────────────────────────────────────

server.registerTool(
  'log',
  {
    description: 'Show the conversation history for a branch without switching to it. Use when the user asks to see previous conversation or history. Call this tool ONCE and relay the output — do NOT call it repeatedly.',
    inputSchema: {
      branch: z.string().optional().describe('Branch name to show history for. Defaults to the active branch.'),
      limit: z.number().optional().describe('Max number of messages to show (default: 20, from most recent).'),
    },
  },
  async ({ branch: branchName, limit }) => {
    const cwd = getCwd();
    const { engine } = createEngine(cwd);
    const ws = await engine.loadWorkspace(WORKSPACE_ID);
    if (!ws) {
      return { content: [{ type: 'text' as const, text: 'No Variantree workspace.' }] };
    }

    const branches = engine.getBranches();
    const target = branchName
      ? branches.find(b => b.name === branchName)
      : branches.find(b => b.isActive);

    if (!target) {
      const names = branches.map(b => b.name).join(', ');
      return { content: [{ type: 'text' as const, text: `✗ Branch "${branchName}" not found. Available: ${names}` }] };
    }

    const allMessages = engine.getContext(target.id);
    if (allMessages.length === 0) {
      return { content: [{ type: 'text' as const, text: `No messages on branch "${target.name}".` }] };
    }

    const cap = limit ?? 20;
    const messages = allMessages.slice(-cap);
    const skipped = allMessages.length - messages.length;

    const lines = [`Conversation history for "${target.name}" (${allMessages.length} total, showing last ${messages.length}):`, ''];
    if (skipped > 0) lines.push(`  ... ${skipped} earlier messages omitted ...`, '');
    for (const msg of messages) {
      if (msg.role === 'system') continue;
      const prefix = msg.role === 'user' ? 'User' : 'Assistant';
      const content = msg.content.length > 200 ? msg.content.slice(0, 200) + '…' : msg.content;
      lines.push(`${prefix}: ${content}`, '');
    }

    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── status ─────────────────────────────────────────────────────

server.registerTool(
  'status',
  {
    description: 'Show current Variantree status. Always relay the COMPLETE output to the user: active branch name, total message count, all branch names, and all checkpoint labels.',
  },
  async () => {
    const cwd = getCwd();
    const { engine } = createEngine(cwd);
    const ws = await engine.loadWorkspace(WORKSPACE_ID);
    if (!ws) {
      return { content: [{ type: 'text' as const, text: 'No Variantree workspace. Use variantree_checkpoint to create one.' }] };
    }

    await syncAndEnsureInstructions(engine, cwd);
    const branch = engine.getActiveBranch();
    const context = engine.getContext();
    const branches = engine.getBranches();
    const checkpoints = engine.getCheckpoints();

    const lines = [
      `Branch: ${branch.name}`,
      `Messages: ${context.length}`,
      `Branches: ${branches.map((b) => `${b.name}${b.isActive ? ' (active)' : ''}`).join(', ')}`,
    ];

    if (checkpoints.length > 0) {
      lines.push('Checkpoints:');
      for (const cp of checkpoints.slice(-8)) {
        lines.push(`  ${cp.snapshotRef ? '◆' : '◇'} ${cp.label}`);
      }
    } else {
      lines.push('Checkpoints: none');
    }
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── tree ───────────────────────────────────────────────────────

server.registerTool(
  'tree',
  {
    description: 'Show ASCII visualization of the full branch and checkpoint tree. Always relay the full output to the user.',
  },
  async () => {
    const cwd = getCwd();
    const { engine } = createEngine(cwd);
    const ws = await engine.loadWorkspace(WORKSPACE_ID);
    if (!ws) {
      return { content: [{ type: 'text' as const, text: 'No Variantree workspace.' }] };
    }

    const branches = engine.getBranches();
    const checkpoints = engine.getCheckpoints().sort((a, b) => a.createdAt - b.createdAt);

    const cpsByBranch = new Map<string, typeof checkpoints>();
    for (const cp of checkpoints) {
      const list = cpsByBranch.get(cp.branchId) ?? [];
      list.push(cp);
      cpsByBranch.set(cp.branchId, list);
    }

    const childBranchesOf = new Map<string, typeof branches>();
    for (const b of branches) {
      if (!b.parentCheckpointId) continue;
      const parentCp = checkpoints.find(c => c.id === b.parentCheckpointId);
      if (!parentCp) continue;
      const siblings = childBranchesOf.get(parentCp.id) ?? [];
      siblings.push(b);
      childBranchesOf.set(parentCp.id, siblings);
    }

    type BranchMeta = (typeof branches)[number];
    type CpMeta = (typeof checkpoints)[number];

    function renderBranch(branch: BranchMeta, prefix: string, connector: string): string[] {
      const active = branch.isActive ? ' ●' : '';
      const out = [`${prefix}${connector}⎇ ${branch.name} (${branch.messageCount} msgs)${active}`];

      const branchCps = cpsByBranch.get(branch.id) ?? [];
      const childIndent = prefix + (connector === '' ? '  ' : (connector.startsWith('└') ? '    ' : '│   '));

      if (branchCps.length === 0) {
        out.push(`${childIndent}└── (no checkpoints)`);
        return out;
      }

      for (let i = 0; i < branchCps.length; i++) {
        const cp = branchCps[i];
        const children = childBranchesOf.get(cp.id) ?? [];
        const isLastCp = i === branchCps.length - 1 && children.length === 0;
        const cpConnector = isLastCp ? '└── ' : '├── ';
        const cpIcon = cp.snapshotRef ? '◆' : '◇';
        out.push(`${childIndent}${cpConnector}${cpIcon} ${cp.label}`);

        const continuation = isLastCp ? '    ' : '│   ';
        for (let j = 0; j < children.length; j++) {
          const isLastChild = j === children.length - 1;
          out.push(...renderBranch(children[j], childIndent + continuation, isLastChild ? '└── ' : '├── '));
        }
      }

      return out;
    }

    const root = branches.find(b => !b.parentCheckpointId);
    if (!root) {
      return { content: [{ type: 'text' as const, text: 'No root branch found.' }] };
    }

    const lines = renderBranch(root, '', '');
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── tree_web ───────────────────────────────────────────────────────────────

server.registerTool(
  'tree_web',
  {
    description:
      'Open an interactive visual tree of all branches and checkpoints in the default browser. ' +
      'Use this when the user asks to "show the tree visually", "open the web UI", or "visualize the tree".',
  },
  async () => {
    const cwd = getCwd();
    const { engine } = createEngine(cwd);
    const ws = await engine.loadWorkspace(WORKSPACE_ID);
    if (!ws) {
      return { content: [{ type: 'text' as const, text: 'No Variantree workspace found. Create a checkpoint first.' }] };
    }

    try {
      const { url } = await openWebUi(ws);
      return {
        content: [{
          type: 'text' as const,
          text: `Opened interactive tree visualization at ${url}\n\nThe browser shows all branches and checkpoints for this project. The view is read-only — use the MCP tools to create checkpoints or branches.`,
        }],
      };
    } catch (err: any) {
      return {
        content: [{
          type: 'text' as const,
          text: `Failed to open web UI: ${err.message}\n\nMake sure the web UI has been built. Run \`npm run build\` in packages/web.`,
        }],
      };
    }
  }
);

// ── stats ──────────────────────────────────────────────────────────────────

/** Per-million-token pricing (USD). */
const MODEL_PRICING: Record<string, { input: number; output: number }> = {
  'claude-opus-4-7': { input: 15, output: 75 },
  'claude-opus-4-6': { input: 15, output: 75 },
  'claude-sonnet-4-7': { input: 3, output: 15 },
  'claude-sonnet-4-5': { input: 3, output: 15 },
  'claude-haiku-3-5': { input: 0.25, output: 1.25 },
};

/** Estimate tokens from content length (~4 chars per token). */
function estimateTokens(content: string): number {
  return Math.ceil(content.length / 4);
}

server.registerTool(
  'stats',
  {
    description:
      'Show per-branch and session-level token analytics. Includes token usage, cost estimates, ' +
      'and tokens saved by branching (compared to a hypothetical linear conversation). ' +
      'Always relay the FULL output to the user.',
  },
  async () => {
    const cwd = getCwd();
    const { engine, snapshotProvider } = await ensureWorkspace(cwd);
    await syncAndEnsureInstructions(engine, cwd);

    const branches = engine.getBranches();
    const checkpoints = engine.getCheckpoints();
    const activeBranch = engine.getActiveBranch();

    // ── Per-branch stats ──────────────────────────────────────────────
    interface BranchStats {
      name: string;
      isActive: boolean;
      messageCount: number;
      userMessages: number;
      assistantMessages: number;
      duration: { startTime: string; endTime: string; durationMinutes: number } | null;
      tokens: {
        inputTokens: number;
        outputTokens: number;
        cacheCreationTokens: number;
        cacheReadTokens: number;
        totalTokens: number;
        method: 'exact' | 'estimated' | 'mixed';
      };
      models: string[];
      checkpointCount: number;
    }

    let sessionTotalInput = 0;
    let sessionTotalOutput = 0;
    let sessionTotalMessages = 0;
    const sessionModels = new Set<string>();
    let sessionMethod: 'exact' | 'estimated' | 'mixed' = 'exact';

    // Collect all message tokens across every branch for linear calculation
    let linearTotalTokens = 0;

    const branchStatsList: BranchStats[] = [];

    for (const branch of branches) {
      const msgs = branch.messages;
      const userMsgs = msgs.filter(m => m.role === 'user');
      const assistantMsgs = msgs.filter(m => m.role === 'assistant');

      let branchInput = 0;
      let branchOutput = 0;
      let branchCacheCreation = 0;
      let branchCacheRead = 0;
      let hasExact = false;
      let hasEstimated = false;
      const branchModels = new Set<string>();

      for (const msg of msgs) {
        if (msg.tokenUsage) {
          branchInput += msg.tokenUsage.inputTokens;
          branchOutput += msg.tokenUsage.outputTokens;
          branchCacheCreation += msg.tokenUsage.cacheCreationTokens ?? 0;
          branchCacheRead += msg.tokenUsage.cacheReadTokens ?? 0;
          if (msg.tokenUsage.model) {
            branchModels.add(msg.tokenUsage.model);
            sessionModels.add(msg.tokenUsage.model);
          }
          if (msg.tokenUsage.method === 'exact') hasExact = true;
          else hasEstimated = true;
        } else {
          // No tokenUsage at all — estimate from content
          const est = estimateTokens(msg.content);
          if (msg.role === 'user') branchInput += est;
          else branchOutput += est;
          hasEstimated = true;
        }
      }

      const branchTotal = branchInput + branchOutput;
      linearTotalTokens += branchTotal;
      sessionTotalInput += branchInput;
      sessionTotalOutput += branchOutput;
      sessionTotalMessages += msgs.length;

      const branchMethod: 'exact' | 'estimated' | 'mixed' =
        hasExact && hasEstimated ? 'mixed' : hasExact ? 'exact' : 'estimated';
      if (branchMethod !== 'exact') sessionMethod = sessionMethod === 'exact' ? branchMethod : 'mixed';

      // Duration
      let duration: BranchStats['duration'] = null;
      if (msgs.length > 0) {
        const first = msgs[0].timestamp;
        const last = msgs[msgs.length - 1].timestamp;
        duration = {
          startTime: new Date(first).toISOString(),
          endTime: new Date(last).toISOString(),
          durationMinutes: Math.round((last - first) / 60000),
        };
      }

      const branchCps = checkpoints.filter(cp => cp.branchId === branch.id);

      branchStatsList.push({
        name: branch.name,
        isActive: branch.isActive,
        messageCount: msgs.length,
        userMessages: userMsgs.length,
        assistantMessages: assistantMsgs.length,
        duration,
        tokens: {
          inputTokens: branchInput,
          outputTokens: branchOutput,
          cacheCreationTokens: branchCacheCreation,
          cacheReadTokens: branchCacheRead,
          totalTokens: branchTotal,
          method: branchMethod,
        },
        models: Array.from(branchModels),
        checkpointCount: branchCps.length,
      });
    }

    // ── Token savings ─────────────────────────────────────────────────
    // Walk the active branch's ancestry to compute branched context size
    const ancestryIds = engine.getAncestry();
    let branchedTotalTokens = 0;
    for (const branchId of ancestryIds) {
      const b = branches.find(br => br.id === branchId);
      if (!b) continue;
      for (const msg of b.messages) {
        if (msg.tokenUsage) {
          branchedTotalTokens += msg.tokenUsage.inputTokens + msg.tokenUsage.outputTokens;
        } else {
          branchedTotalTokens += estimateTokens(msg.content);
        }
      }
    }

    const tokensSaved = Math.max(0, linearTotalTokens - branchedTotalTokens);
    const percentReduction = linearTotalTokens > 0
      ? ((tokensSaved / linearTotalTokens) * 100).toFixed(1)
      : '0.0';

    // Cost estimation
    const primaryModel = sessionModels.size > 0 ? Array.from(sessionModels)[0] : null;
    const pricing = primaryModel ? MODEL_PRICING[primaryModel] ?? null : null;
    let estimatedCostSaved = 'N/A';
    if (pricing) {
      const inputSaved = tokensSaved * 0.5; // rough 50/50 split
      const outputSaved = tokensSaved * 0.5;
      const cost = (inputSaved / 1_000_000) * pricing.input + (outputSaved / 1_000_000) * pricing.output;
      estimatedCostSaved = `$${cost.toFixed(4)}`;
    }

    // ── Format output ─────────────────────────────────────────────────
    const lines: string[] = [];
    lines.push('📊 Variantree Session Stats', '');

    // Per-branch
    lines.push('── Per-Branch ──────────────────────────────────');
    for (const bs of branchStatsList) {
      const active = bs.isActive ? ' ● (active)' : '';
      lines.push(`  ⎇ ${bs.name}${active}`);
      lines.push(`    Messages: ${bs.messageCount} (${bs.userMessages} user, ${bs.assistantMessages} assistant)`);
      lines.push(`    Tokens: ${bs.tokens.totalTokens.toLocaleString()} (in: ${bs.tokens.inputTokens.toLocaleString()}, out: ${bs.tokens.outputTokens.toLocaleString()}) [${bs.tokens.method}]`);
      if (bs.tokens.cacheCreationTokens > 0 || bs.tokens.cacheReadTokens > 0) {
        lines.push(`    Cache: ${bs.tokens.cacheReadTokens.toLocaleString()} read, ${bs.tokens.cacheCreationTokens.toLocaleString()} created`);
      }
      if (bs.models.length > 0) lines.push(`    Model: ${bs.models.join(', ')}`);
      if (bs.duration) lines.push(`    Duration: ${bs.duration.durationMinutes} min`);
      lines.push(`    Checkpoints: ${bs.checkpointCount}`);
      lines.push('');
    }

    // Session totals
    lines.push('── Session Totals ──────────────────────────────');
    lines.push(`  Branches: ${branches.length}`);
    lines.push(`  Checkpoints: ${checkpoints.length}`);
    lines.push(`  Messages: ${sessionTotalMessages}`);
    lines.push(`  Tokens: ${(sessionTotalInput + sessionTotalOutput).toLocaleString()} (in: ${sessionTotalInput.toLocaleString()}, out: ${sessionTotalOutput.toLocaleString()}) [${sessionMethod}]`);
    if (sessionModels.size > 0) lines.push(`  Models: ${Array.from(sessionModels).join(', ')}`);
    lines.push('');

    // Token savings
    lines.push('── Token Savings (branching vs linear) ─────────');
    lines.push(`  Linear context (all branches): ${linearTotalTokens.toLocaleString()} tokens`);
    lines.push(`  Branched context (active path): ${branchedTotalTokens.toLocaleString()} tokens`);
    lines.push(`  Tokens saved: ${tokensSaved.toLocaleString()} (${percentReduction}% reduction)`);
    lines.push(`  Estimated cost saved: ${estimatedCostSaved}`);
    lines.push(`  Method: ${sessionMethod}`);

    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── Start ─────────────────────────────────────────────────────────────────

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('[variantree-mcp] Server running on stdio');
}

main().catch((err) => {
  console.error('[variantree-mcp] Fatal:', err);
  process.exit(1);
});
