#!/usr/bin/env node
/**
 * @variantree/mcp — MCP Server
 *
 * Exposes Variantree operations as MCP tools that AI coding assistants
 * (OpenCode, Claude Code, etc.) can call during conversations.
 *
 * Transport: stdio (spawned as child process by the host).
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import path from 'node:path';
import fs from 'node:fs';
import { VariantTree } from '@variantree/core';
import {
  NodeStorage,
  NodeBlobStore,
  NodeFileSystem,
  OpenCodeAdapter,
  MessageDiffer,
} from '@variantree/watcher';

// ─── Shared Helpers ───────────────────────────────────────────────────────

const WORKSPACE_ID = 'default';

function getCwd(): string {
  return process.env.VARIANTREE_DIR
    ? path.resolve(process.env.VARIANTREE_DIR)
    : process.cwd();
}

function createEngine(cwd: string) {
  const storage = new NodeStorage(cwd);
  const engine = new VariantTree({
    storage,
    snapshotStorage: new NodeBlobStore(cwd),
    fileSystem: new NodeFileSystem(),
  });
  return { engine, storage };
}

async function ensureWorkspace(cwd: string) {
  const { engine, storage } = createEngine(cwd);
  let ws = await engine.loadWorkspace(WORKSPACE_ID);
  if (!ws) {
    ws = await engine.createWorkspace('My Project');
    ws.id = WORKSPACE_ID;
    await storage.save(WORKSPACE_ID, ws);
    await engine.loadWorkspace(WORKSPACE_ID);
  }
  return { engine, storage };
}

async function syncConversation(engine: VariantTree, cwd: string): Promise<number> {
  const adapter = new OpenCodeAdapter();
  const messages = await adapter.readMessagesAsync(cwd);
  if (messages.length === 0) return 0;

  const existing = engine.getContext();
  const differ = new MessageDiffer();
  differ.diff(existing);
  const newMessages = differ.diff(messages);

  for (const msg of newMessages) {
    await engine.addMessage(msg.role, msg.content, { source: 'opencode' });
  }
  return newMessages.length;
}

function generateContextFile(cwd: string, branchName: string, messages: Array<{ role: string; content: string }>) {
  const contextDir = path.join(cwd, '.variantree');
  if (!fs.existsSync(contextDir)) fs.mkdirSync(contextDir, { recursive: true });

  const lines = [
    `# Variantree Branch Context`,
    ``,
    `**Branch:** ${branchName}`,
    `**Generated:** ${new Date().toISOString()}`,
    ``,
    `> Auto-generated by Variantree. Read this for context on prior work.`,
    ``,
    `---`,
    ``,
    `## Conversation History`,
    ``,
  ];

  for (const msg of messages) {
    const prefix = msg.role === 'user' ? '**User:**' : '**Assistant:**';
    const content = msg.content.length > 500 ? msg.content.slice(0, 500) + '...' : msg.content;
    lines.push(`${prefix} ${content}`, '');
  }

  fs.writeFileSync(path.join(contextDir, 'branch-context.md'), lines.join('\n'), 'utf8');
}

// ─── MCP Server ───────────────────────────────────────────────────────────

const server = new McpServer({
  name: 'variantree',
  version: '0.1.0',
});

// ── checkpoint ─────────────────────────────────────────────────

// @ts-expect-error — MCP SDK's Zod type inference is excessively deep (TS2589)
server.tool(
  'checkpoint',
  'Create a Variantree checkpoint: syncs the current conversation from the AI coding tool and takes a snapshot of all code files. Use this when the user wants to save progress.',
  { label: z.string().describe('A short label for this checkpoint, e.g. "auth-working"') },
  async ({ label }) => {
    const cwd = getCwd();
    const { engine } = await ensureWorkspace(cwd);
    const synced = await syncConversation(engine, cwd);
    const cp = await engine.createCheckpoint(label, { workspacePath: cwd });

    const totalMessages = engine.getContext().length;
    const lines = [`✓ Checkpoint "${label}" created.`];
    lines.push(`  Messages synced: ${synced} new  (${totalMessages} total in context)`);

    if (cp.snapshot) {
      const allCheckpoints = engine.getCheckpoints();
      const activeBranch = engine.getActiveBranch();

      // First look for a previous checkpoint on the same branch,
      // then fall back to the parent checkpoint this branch was forked from
      const prevCp =
        allCheckpoints
          .filter(c => c.id !== cp.id && c.branchId === cp.branchId && c.snapshot)
          .sort((a, b) => b.createdAt - a.createdAt)[0] ??
        (activeBranch.parentCheckpointId
          ? allCheckpoints.find(c => c.id === activeBranch.parentCheckpointId && c.snapshot)
          : undefined);

      if (prevCp?.snapshot) {
        const prevPaths = new Map(prevCp.snapshot.files.map(f => [f.path, f.hash]));
        const newPaths = new Map(cp.snapshot.files.map(f => [f.path, f.hash]));
        const added = [...newPaths.keys()].filter(p => !prevPaths.has(p)).length;
        const deleted = [...prevPaths.keys()].filter(p => !newPaths.has(p)).length;
        const modified = [...newPaths.keys()].filter(p => prevPaths.has(p) && prevPaths.get(p) !== newPaths.get(p)).length;
        const parts = [];
        if (added > 0) parts.push(`+${added} added`);
        if (modified > 0) parts.push(`~${modified} modified`);
        if (deleted > 0) parts.push(`-${deleted} deleted`);
        lines.push(`  Snapshot: ${parts.length > 0 ? parts.join('  ') : 'no file changes'}  (${cp.snapshot.fileCount} files total)`);
      } else {
        lines.push(`  Snapshot: ${cp.snapshot.fileCount} files  (${(cp.snapshot.totalSize / 1024).toFixed(1)} KB)`);
      }
    }
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── branch ─────────────────────────────────────────────────────

server.tool(
  'branch',
  'Create a new Variantree branch. Restores code to the checkpoint state and generates a context file for the new session.',
  {
    name: z.string().describe('Branch name, e.g. "try-graphql"'),
    checkpoint: z.string().optional().describe('Checkpoint label to branch from. Defaults to latest.'),
  },
  async ({ name, checkpoint }) => {
    const cwd = getCwd();
    const { engine } = await ensureWorkspace(cwd);
    await syncConversation(engine, cwd);

    let cpId: string | undefined;
    let cpLabel = 'current state';

    if (checkpoint) {
      const allCheckpoints = engine.getCheckpoints();
      const cp = allCheckpoints.find((c) => c.label === checkpoint);
      if (!cp) {
        return { content: [{ type: 'text' as const, text: `✗ Checkpoint "${checkpoint}" not found. Available: ${allCheckpoints.map((c) => c.label).join(', ') || 'none'}` }] };
      }
      cpId = cp.id;
      cpLabel = cp.label;
    }

    // Branch will auto-checkpoint if cpId is undefined
    const branch = await engine.branch(name, cpId);
    const lines = [
      `✓ Branch "${name}" created from ${checkpoint ? `"${cpLabel}"` : 'current un-checkpointed state'} and switched to it.`,
      `⚡ IMPORTANT: Tell the user to restart this session now. At the start of the new session, your first action must be to read the file .variantree/branch-context.md to restore prior context.`,
    ];

    // Only restore files if we explicitly branched from an older checkpoint
    if (cpId && checkpoint) {
      const summary = await engine.restoreCheckpoint(cpId, cwd);
      // restoreCheckpoint switches to the checkpoint's parent branch as a side effect —
      // switch back to the newly created branch
      await engine.switchBranch(branch.id);
      if (summary) {
        lines.push(`  Restored backward: ${summary.written.length} files written, ${summary.deleted.length} deleted.`);
      }
    }

    generateContextFile(cwd, name, engine.getContext());
    lines.push(`  Context file written: .variantree/branch-context.md`);
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── switch ─────────────────────────────────────────────────────

server.tool(
  'switch',
  'Switch to an existing Variantree branch. This will overwrite your files with the branch\'s latest checkpoint and generate a new context file.',
  { name: z.string().describe('Name of the existing branch to switch to, e.g. "main" or "dev"') },
  async ({ name }) => {
    const cwd = getCwd();
    const { engine } = await ensureWorkspace(cwd);

    const branches = engine.getBranches();
    const targetBranch = branches.find((b) => b.name === name);
    if (!targetBranch) {
      return { content: [{ type: 'text' as const, text: `✗ Branch "${name}" not found. Available: ${branches.map(b => b.name).join(', ')}` }] };
    }

    if (targetBranch.isActive) {
      return { content: [{ type: 'text' as const, text: `Already on branch "${name}".` }] };
    }

    await engine.switchBranch(targetBranch.id);

    const checkpoints = engine.getCheckpoints().filter(c => c.branchId === targetBranch.id);
    const latestCp = checkpoints[checkpoints.length - 1];
    const lines = [`✓ Switched to branch "${name}".`];

    if (latestCp) {
       const summary = await engine.restoreCheckpoint(latestCp.id, cwd);
       if (summary) {
         lines.push(`  Restored to checkpoint "${latestCp.label}": ${summary.written.length} files written, ${summary.deleted.length} deleted.`);
       }
    } else {
       lines.push(`  (No checkpoints found on this branch to restore state.)`);
    }

    generateContextFile(cwd, name, engine.getContext());
    lines.push(`  Context updated: .variantree/branch-context.md`);
    lines.push(`⚡ CRITICAL: You must restart OpenCode (or clear your session) and read .variantree/branch-context.md to load the new branch context!`);

    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── restore ────────────────────────────────────────────────────

server.tool(
  'restore',
  'Restore code files to the state at a specific checkpoint. Generates a context file with conversation history.',
  { label: z.string().describe('Checkpoint label to restore to') },
  async ({ label }) => {
    const cwd = getCwd();
    const { engine } = await ensureWorkspace(cwd);

    const cp = engine.getCheckpoints().find((c) => c.label === label);
    if (!cp) {
      return { content: [{ type: 'text' as const, text: `✗ Checkpoint "${label}" not found.` }] };
    }

    const summary = await engine.restoreCheckpoint(cp.id, cwd);
    const lines: string[] = [];

    if (summary) {
      lines.push(`✓ Restored to "${label}": ${summary.written.length} written, ${summary.deleted.length} deleted.`);
    } else {
      lines.push(`✓ Switched to "${label}" (no snapshot).`);
    }

    generateContextFile(cwd, engine.getActiveBranch().name, engine.getContext());
    lines.push(`  Context updated: .variantree/branch-context.md`);
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── log ────────────────────────────────────────────────────────

server.tool(
  'log',
  'Show the conversation history for a branch without switching to it or modifying any files. Use this when the user asks to see previous conversation, history, or what was discussed on a branch.',
  { branch: z.string().optional().describe('Branch name to show history for. Defaults to the active branch.') },
  async ({ branch: branchName }) => {
    const cwd = getCwd();
    const { engine } = createEngine(cwd);
    const ws = await engine.loadWorkspace(WORKSPACE_ID);
    if (!ws) {
      return { content: [{ type: 'text' as const, text: 'No Variantree workspace.' }] };
    }

    const branches = engine.getBranches();
    const target = branchName
      ? branches.find(b => b.name === branchName)
      : branches.find(b => b.isActive);

    if (!target) {
      const names = branches.map(b => b.name).join(', ');
      return { content: [{ type: 'text' as const, text: `✗ Branch "${branchName}" not found. Available: ${names}` }] };
    }

    const messages = engine.getContext(target.id);
    if (messages.length === 0) {
      return { content: [{ type: 'text' as const, text: `No messages on branch "${target.name}".` }] };
    }

    const lines = [`Conversation history for "${target.name}" (${messages.length} messages):`, ''];
    for (const msg of messages) {
      if (msg.role === 'system') continue;
      const prefix = msg.role === 'user' ? 'User' : 'Assistant';
      const content = msg.content.length > 400 ? msg.content.slice(0, 400) + '…' : msg.content;
      lines.push(`${prefix}: ${content}`, '');
    }

    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── status ─────────────────────────────────────────────────────

server.tool(
  'status',
  'Show current Variantree status: active branch, messages, all branches, and checkpoints.',
  {},
  async () => {
    const cwd = getCwd();
    const { engine } = createEngine(cwd);
    const ws = await engine.loadWorkspace(WORKSPACE_ID);
    if (!ws) {
      return { content: [{ type: 'text' as const, text: 'No Variantree workspace. Use variantree_checkpoint to create one.' }] };
    }

    await syncConversation(engine, cwd);
    const branch = engine.getActiveBranch();
    const context = engine.getContext();
    const branches = engine.getBranches();
    const checkpoints = engine.getCheckpoints();

    const lines = [
      `Branch: ${branch.name}`,
      `Messages: ${context.length}`,
      `Branches: ${branches.map((b) => `${b.name}${b.isActive ? ' (active)' : ''}`).join(', ')}`,
    ];

    if (checkpoints.length > 0) {
      lines.push('Checkpoints:');
      for (const cp of checkpoints.slice(-8)) {
        lines.push(`  • ${cp.label}${cp.snapshot ? ' 📸' : ''}`);
      }
    } else {
      lines.push('Checkpoints: none');
    }
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── tree ───────────────────────────────────────────────────────

server.tool(
  'tree',
  'Show ASCII visualization of the branch/checkpoint tree.',
  {},
  async () => {
    const cwd = getCwd();
    const { engine } = createEngine(cwd);
    const ws = await engine.loadWorkspace(WORKSPACE_ID);
    if (!ws) {
      return { content: [{ type: 'text' as const, text: 'No Variantree workspace.' }] };
    }

    const branches = engine.getBranches();
    const checkpoints = engine.getCheckpoints();

    // Build a branch-to-children map (skip checkpoint layer)
    const cpById = new Map(checkpoints.map(c => [c.id, c]));
    const childrenOf = new Map<string, typeof branches>();
    for (const b of branches) {
      if (!b.parentCheckpointId) continue;
      const parentCp = cpById.get(b.parentCheckpointId);
      if (!parentCp) continue;
      const siblings = childrenOf.get(parentCp.branchId) ?? [];
      siblings.push(b);
      childrenOf.set(parentCp.branchId, siblings);
    }

    type BranchMeta = (typeof branches)[number];

    function renderBranch(branch: BranchMeta, prefix: string, connector: string): string[] {
      const active = branch.isActive ? ' (active)' : '';
      const out = [`${prefix}${connector}${branch.name}${active}`];
      const children = childrenOf.get(branch.id) ?? [];
      for (let i = 0; i < children.length; i++) {
        const isLast = i === children.length - 1;
        const childPrefix = prefix + (connector === '' ? '' : (connector.startsWith('└') ? '    ' : '│   '));
        out.push(...renderBranch(children[i], childPrefix, isLast ? '└── ' : '├── '));
      }
      return out;
    }

    const root = branches.find(b => !b.parentCheckpointId);
    if (!root) {
      return { content: [{ type: 'text' as const, text: 'No root branch found.' }] };
    }

    const lines = renderBranch(root, '', '');
    return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
  }
);

// ── Start ─────────────────────────────────────────────────────────────────

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('[variantree-mcp] Server running on stdio');
}

main().catch((err) => {
  console.error('[variantree-mcp] Fatal:', err);
  process.exit(1);
});
